model_args:
  backbone: prithvi_eo_v2_100_tl
  backbone_pretrained: true
  backbone_num_frames: 3
  backbone_coords_encoding:
  - time
  - location
  backbone_bands:
  - BLUE
  - GREEN
  - RED
  - NIR_NARROW
  rescale: true
  necks:
  - name: SelectIndices
    indices:
    - 2
    - 5
    - 8
    - 11
  - name: ReshapeTokensToImage
    effective_time_dim: 3
  decoder: UperNetDecoder
  decoder_channels: 256
  head_dropout: 0.2
  num_classes: 13
model_factory: EncoderDecoderFactory
model: null
loss: ce
aux_heads: null
aux_loss: null
class_weights:
- 0.386375
- 0.661126
- 0.548184
- 0.640482
- 0.876862
- 0.925186
- 3.249462
- 1.542289
- 2.175141
- 2.272419
- 3.062762
- 3.626097
- 1.198702
ignore_index: -1
lr: 0.001
optimizer: null
optimizer_hparams: null
scheduler: null
scheduler_hparams: null
freeze_backbone: true
freeze_decoder: false
freeze_head: false
plot_on_val: false
class_names:
- Natural Vegetation
- Forest
- Corn
- Soybeans
- Wetlands
- Developed / Barren
- Open Water
- Winter Wheat
- Alfalfa
- Fallow / Idle Cropland
- Cotton
- Sorghum
- Other
tiled_inference_parameters: null
test_dataloaders_names: null
lr_overrides: null
output_on_inference: prediction
output_most_probable: true
path_to_record_metrics: null
tiled_inference_on_testing: false
tiled_inference_on_validation: false
evaluation_output_dir: outputs/prithvi_4band_europe_replay/evaluation
initial_checkpoint: outputs/prithvi_4band_augmented_refine/checkpoints/epoch=06-macro_f1=0.5051.ckpt
crop_binary_loss_weight: 0.25
_instantiator: lightning.pytorch.cli.instantiate_module
