"""Stable contracts shared by training, payload and ground components."""

from prithvi_shared.bands import (
    INPUT_HEIGHT,
    INPUT_WIDTH,
    MODEL_BANDS,
    NORMALIZATION_MEANS,
    NORMALIZATION_STDS,
    TIME_STEPS,
)
from prithvi_shared.calibration import (
    CROP_CLASSIFICATION_THRESHOLD,
    HEALTH_ANALYSIS_CROP_THRESHOLD,
    SELECTED_CHECKPOINT_NAME,
    SELECTED_CHECKPOINT_SHA256,
    SOURCE_CHECKPOINT_SHA256,
)
from prithvi_shared.classes import (
    BINARY_CROP_TARGET_IDS,
    BINARY_IGNORE_CLASS_IDS,
    CLASS_NAMES,
    CROP_PROBABILITY_CLASS_IDS,
    HEALTH_CROP_CLASS_IDS,
    NON_CROP_CLASS_IDS,
)

__all__ = [
    "BINARY_CROP_TARGET_IDS",
    "BINARY_IGNORE_CLASS_IDS",
    "CLASS_NAMES",
    "CROP_CLASSIFICATION_THRESHOLD",
    "CROP_PROBABILITY_CLASS_IDS",
    "HEALTH_ANALYSIS_CROP_THRESHOLD",
    "HEALTH_CROP_CLASS_IDS",
    "INPUT_HEIGHT",
    "INPUT_WIDTH",
    "MODEL_BANDS",
    "NON_CROP_CLASS_IDS",
    "NORMALIZATION_MEANS",
    "NORMALIZATION_STDS",
    "SELECTED_CHECKPOINT_NAME",
    "SELECTED_CHECKPOINT_SHA256",
    "SOURCE_CHECKPOINT_SHA256",
    "TIME_STEPS",
]
